### ISSUE TITLE
staudenmeir/eloquent-eager-limit v1.0 requires illuminate/database ~5.5.29|5.6.*|5.7.*

### ISSUE THREAD

**Issue by Mohammad-Ha** [staudenmeir/eloquent-eager-limit#11]
I recently upgraded to Laravel 5.8 and had to remove this package to be able to upgrade. After upgrading, I tried to install this package and experienced the same issue. I'm pretty sure that this package supports 5.8 (Stated in the comments of the migrations), but I'm unable to know why this occurs.

composer.json: 

`"require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "imdbphp/imdbphp": "^6.2",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "reinink/advanced-eloquent": "^0.2.0",
        "staudenmeir/eloquent-eager-limit": "1.0",
        "tymon/jwt-auth": "^1.0.0-rc.3",
        "venturecraft/revisionable": "1.*"
    }`

**Comment by staudenmeir** [comment]
Version `1.3` supports Laravel 5.8.

I would recommend that you use `"staudenmeir/eloquent-eager-limit": "^1.0"` in your `composer.json` file.

This way, you always get the compatible version automatically.
