### ISSUE TITLE
Oracle Support

### ISSUE THREAD

**Issue by mhelaiwa** [staudenmeir/eloquent-eager-limit#12]
Is there any progress for supporting Oracel Database?

Thank you :)

**Comment by staudenmeir** [comment]
I'll look into it.

**Comment by staudenmeir** [comment]
Are you using the `yajra/laravel-oci8` package?

**Comment by enghelewa** [comment]
Yes, That's right. [This is the grummer file](https://github.com/yajra/laravel-oci8/blob/5.8/src/Oci8/Schema/Grammars/OracleGrammar.php) if it may helps you.

Thank you very much for your concern in this improvement .. I really appreciate that 🥇

**Comment by staudenmeir** [comment]
Unfortunately, the package's queries need to be adjusted to work on Oracle.

This may take a while. Installing Oracle is a nightmare...

**Comment by staudenmeir** [comment]
Do you by chance have working instructions to install Oracle in Homestead?
