### ISSUE TITLE
HasMany attach

### ISSUE THREAD

**Issue by FrieNze** [staudenmeir/eloquent-eager-limit#13]
Call to undefined method Staudenmeir\EloquentEagerLimit\Relations\HasMany::attach()

`$category->products()->attach($products)`

**Comment by staudenmeir** [comment]
`HasMany` relationships don't have an `attach()` method: https://laravel.com/docs/eloquent-relationships#inserting-and-updating-related-models

**Comment by FrieNze** [comment]
Oh real. I'm sorry
