### ISSUE TITLE
FEATURE REQUEST: Allow paginating when eager loading

### ISSUE THREAD

**Issue by abishekrsrikaanth** [staudenmeir/eloquent-eager-limit#15]
So far loving this package. Very helpful. 
Would it be possible to make use of the `paginate` function? 

```
 $category = $this->getQuery()->with(['products' => function ($query)  {
            $query->paginate();
        }])->first();
```

What I am trying to do is show products within a category, but I want to paginate the products. 
If this is out of the package's scope, can you suggest a good way to do this?
Not sure if this is a dumb question?

**Comment by staudenmeir** [comment]
Eager loading can't be used for pagination queries. Use lazy loading instead:

```php
$category = $this->getQuery()->first();

$products = $category->products()->paginate();
```

If you want to access the products with `$category->products`:

```php
$category->setRelation('products', $products);
```

**Comment by abishekrsrikaanth** [comment]
@staudenmeir, sounds good. Appreciate it.
