### ISSUE TITLE
Does it support hasmanythrough?

### ISSUE THREAD

**Issue by thanh858036** [staudenmeir/eloquent-eager-limit#17]
i have table
Category many to many comic, has many through chapter
Comic has many chapter
I use
```
$ category = Category :: where ('slug', $ categorySlug) -> with (['comics.chapters' => function ($ query) {
             $ query-> latest () -> limit (3);
         }]) -> get ();
```
But how to sort comic table by updated_at?

**Comment by staudenmeir** [comment]
Please post both relationships.

**Comment by thanh858036** [comment]
Category Model
```
public function comics()
    {
        return $this->belongsToMany(Comic::class);
    }

    public function chapters()
    {
        return $this->hasManyThrough(Chapter::class, Comic::class);
    }
```
Comic Model
```
    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }

    public function chapters()
    {
        return $this->hasMany(Chapter::class);
    }
```
Chapter Model
```
public function comic()
    {
        return $this->belongsTo(Comic::class);
    }
```
How to 1 category can get all comics and each comic get limit 3 chapter and orderBy Comic id

**Comment by staudenmeir** [comment]
> But how to sort comic table by updated_at?
> each comic get limit 3 chapter and orderBy Comic id

Do you want to order comics or chapters or both?

**Comment by thanh858036** [comment]
I want both comics and chapters newest to oldest

**Comment by staudenmeir** [comment]
Do you mean this?

```php
$category = Category::where('slug', $categorySlug)->with(['comics' => function ($query) {
    $query->latest()->with(['chapters' => function ($query) {
        $query->latest()->limit(3);
    }]);
}])->get();
```

**Comment by thanh858036** [comment]
> Do you mean this?
> 
> ```
> $category = Category::where('slug', $categorySlug)->with(['comics' => function ($query) {
>     $query->latest()->with(['chapters' => function ($query) {
>         $query->latest()->limit(3);
>     }]);
> }])->get();
> ```

yes thank you

**Comment by thanh858036** [comment]
does it support both limit and paginate

**Comment by staudenmeir** [comment]
Which relationship do you want to paginate?

**Comment by thanh858036** [comment]
> Do you mean this?
> 
> ```
> $category = Category::where('slug', $categorySlug)->with(['comics' => function ($query) {
>     $query->latest()->with(['chapters' => function ($query) {
>         $query->latest()->limit(3);
>     }]);
> }])->get();
> ```

i want this query and paginate by comics

**Comment by staudenmeir** [comment]
```php
$category = Category::where('slug', $categorySlug)->first();

$comics = $category->comics()->latest()->with(['chapters' => function ($query) {
    $query->latest()->limit(3);
}])->paginate(10);
```
