### ISSUE TITLE
Call to undefined method groupLimit() on lumen

### ISSUE THREAD

**Issue by xieguo** [staudenmeir/eloquent-eager-limit#18]
Call to undefined method Illuminate\Database\Eloquent\Builder::groupLimit() on lumen 5.8.*

Use the `HasEagerLimit` trait in both the parent and the related model: post and comment.

code  
```
$result = Post::with(['comment' => function ($query) {
            $query->latest()->limit(10);
        }])->get();

return $result;
```

**Comment by staudenmeir** [comment]
Please post both models.
