### ISSUE TITLE
Trait-based implementation 

### ISSUE THREAD

**Issue by mpyw** [staudenmeir/eloquent-eager-limit#19]
I'd like to use the following two library. Both of them have nice features.

- [staudenmeir/eloquent-eager-limit: Laravel Eloquent eager loading with limit](https://github.com/staudenmeir/eloquent-eager-limit)
- [topclaudy/compoships: Multi-columns relationships for Laravel's Eloquent ORM](https://github.com/topclaudy/compoships)

However, each `Builder` `Relation` is extended from Eloquent core. It's a little hard to go on with both of them.

Would you prefer to refactor them into Trait-based implementation?

Related: topclaudy/compoships#64

**Comment by staudenmeir** [comment]
How would that look like?

**Comment by mpyw** [comment]
Like this: 

https://github.com/mpyw/laravel-mysql-system-variable-manager/blob/14864ae653019eadf9fca584cff3b298856ba6d9/src/MySqlConnection.php

Logic are written in traits, and extended classes as default implementation just use it.

**Comment by mpyw** [comment]
I've just tried to manually mixin (partially allowing copy and paste) and go on with both of them, but accidentally caused serious bugs...

**Comment by mpyw** [comment]
Okay I'll try as a library 😂

[mpyw/compoships-eager-limit: topclaudy/compoships + staudenmeir/eloquent-eager-limit](https://github.com/mpyw/compoships-eager-limit)

**Comment by mpyw** [comment]
Tested 100%

**Comment by mpyw** [comment]
@staudenmeir Would you review my code and join as a collaborator?
