### ISSUE TITLE
Not working on Plesk

### ISSUE THREAD

**Issue by Julianvschijndel** [staudenmeir/eloquent-eager-limit#26]
Hi, first of all thanks for this awesome package. I use this to develop a forum. It works when I'm using localhost and when I switch to my Plesk database with below data:

Versie database-server | Type database-server
-- | --
10.1.44 | MySQL / MariaDB / Percona

I tried to change the strict to false in `config/database.php` but that also doesn't work. Do you have a fixing code maybe?

Below is the error code I get:
``
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(partition by `threads`.`forum_id` order by `last_post_date` desc) as laravel_ro' at line 1 (SQL: select * from (select *, row_number() over (partition by `threads`.`forum_id` order by `last_post_date` desc) as laravel_row from `threads` where `threads`.`forum_id` in (1, 2, 3, 4)) as laravel_table where laravel_row <= 1 order by laravel_row)
``

**Comment by staudenmeir** [comment]
The package relies on window functions that are only available in MariaDB 10.2+.

**Comment by Julianvschijndel** [comment]
Hi, @staudenmeir ,
Thanks for the quick response. So if I have a MariaDB with a version higher then 10.2+ it will work?

**Comment by staudenmeir** [comment]
Yes.

**Comment by Julianvschijndel** [comment]
Alright then, I will search for a solution. Thanks for the quick responses.
