### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by sayhicoelho** [staudenmeir/eloquent-eager-limit#28]
Thanks for the package! It works! But we've a problem: performance!

It's taking between 6~7 seconds to return the results.

My code:

```php
Route::get('/users', function (Request $request) {
    $data = User::withCount('posts')->with(['posts' => function ($q) {
        $q->latest()->limit(3);
    }])->limit(10)->get();

    return response()->json($data);
});
```

As I mentioned, it's working as expected. But it's taking a long time to complete the query. Is it a database limitation or the query is malformed by the package?

I've 500,000 fake posts generated just for testing purposes.

I've tested the same example but without the package using lazy load query.

My code:

```php
Route::get('/users', function (Request $request) {
    $data = User::withCount('posts')->limit(10)->get()->map(function ($user) {
        $user->setRelation('posts', $user->posts()->limit(3)->get());
        return $user;
    });

    return response()->json($data);
});
```

The above code returns the expected result as the package does, but it has returned the results in just 150~200 ms.

Am I missing something to improve performance using the package?

**Comment by staudenmeir** [comment]
What database and version are you using?

**Comment by sayhicoelho** [comment]
10.4.13-MariaDB

**Comment by staudenmeir** [comment]
Please post the `posts` migration. Are you using indexes?

Can you share the testing data?

**Comment by sayhicoelho** [comment]
Hey @staudenmeir! Thanks for the feedback!

Here is my posts migration:

```php
Schema::create('posts', function (Blueprint $table) {
    $table->id();
    $table->foreignId('author_id')->constrained('users')->onDelete('cascade');
    $table->foreignId('category_id')->constrained('categories')->onDelete('cascade');
    $table->string('title');
    $table->string('slug');
    $table->text('body');
    $table->string('excerpt');
    $table->enum('status', ['pending', 'published']);
    $table->timestamps();
});
```

I can send you the entire data, but it's almost 110MB.

Uploaded file: https://we.tl/t-MZ1mPP3xue

**Comment by staudenmeir** [comment]
> Is it a database limitation or the query is malformed by the package?

The query is correct.

The query is slow because MariaDB doesn't use the `author_id` index. Are these posts a realistic representation of your actual data (very few users with tens of thousands of posts each)?

**Comment by sayhicoelho** [comment]
Got it.

I'll try to do these tests with PostgreSQL soon.

I've used these thousands of data to test the query performance and in a scenario when I'd have thousands of related data I'll have problems with this package.
