### ISSUE TITLE
Custom pivot alias is throwing an error

### ISSUE THREAD

**Issue by danilopolani** [staudenmeir/eloquent-eager-limit#31]
I'm trying to use this package with a custom pivot alias like this:

```php
public function licenses(): BelongsToMany
  {
    return $this->belongsToMany('App\License')
      ->using('App\CitizenLicense')
      ->as('status')
      ->withPivot('id')
      ->withTimestamps();
  }
```

With this code an exception is thrown:

> Call to a member function newCollection() on null

Related to the method `eagerLoadPivotRelations` of the package (the second line):

```php
protected function eagerLoadPivotRelations($models, $pivotAccessor)
    {
        $pivots = Arr::pluck($models, $pivotAccessor);
        $pivots = head($pivots)->newCollection($pivots);
        $pivots->load($this->getPivotEagerLoadRelations($pivotAccessor));
    }
```

If I remove the `as('status')` from the relationship, it works fine. Note that I'm using this along with [eager-load-pivot-relationship](https://github.com/ajcastro/eager-load-pivot-relations) package if it matters.

**Comment by staudenmeir** [comment]
How are you using the `licenses` relationship?

**Comment by danilopolani** [comment]
Oh sorry, the relationship is used like this (in the `CitizenLicense` model):

```php
/**
  * Get the latest log about a status change.
  *
  * @return \Illuminate\Database\Eloquent\Relations\HasMany
  */
  public function latestStatusLog(): HasMany
  {
    return $this->hasMany('App\CitizenLicenseLog', 'pivot_id')
      ->where('action', 'not like', 'undo_%')
      ->latest()
      ->limit(1);
  }
```

Then this relationship on the pivot model is loaded (thanks to the eager-load-pivot-relationship package) like this:

```php
/**
  * Show a citizen.
  *
  * @param  \App\Citizen $citizen
  * @return \Illuminate\View\View
  */
  public function show(Citizen $citizen): View
  {
    $citizen->load('licenses.pivot.latestStatusLog');
  }
```

**Comment by staudenmeir** [comment]
Please see https://github.com/ajcastro/eager-load-pivot-relations#custom-pivot-accessor.

You need to use `EagerLoadPivotTrait` in the `Citizen` model and also use the custom pivot accessor for eager loading:

```php
  public function show(Citizen $citizen): View
  {
    $citizen->load('licenses.status.latestStatusLog');
  }                          ^^^^^^
```

**Comment by danilopolani** [comment]
Omg I didn't notice that, thank you! It totally solves the problem
