### ISSUE TITLE
Conflict Trait

### ISSUE THREAD

**Issue by ukik** [staudenmeir/eloquent-eager-limit#38]
when i use below traits in a class, there is error

use \Staudenmeir\EloquentEagerLimit\HasEagerLimit;
use \Awobaz\Compoships\Compoships;

**Comment by adamhopkinson** [comment]
What's the error?

**Comment by elyash14** [comment]
I have the same issue when using this trait with other traits like caching traits. It seems there are name collisions on the newRelations methods.
The error:
Trait method newBelongsToMany has not been applied, because there are collisions with other trait methods on App\Models\Category

**Comment by mpyw** [comment]
Hi

[mpyw/compoships-eager-limit: topclaudy/compoships + staudenmeir/eloquent-eager-limit](https://github.com/mpyw/compoships-eager-limit)

**Comment by staudenmeir** [comment]
Thanks @mpyw!

@elyash14 Which other traits are you trying to use together with this package?

**Comment by Joemires** [comment]
https://github.com/dwightwatson/rememberable & https://github.com/GeneaLabs/laravel-model-caching doesn't work with the package
