### ISSUE TITLE
Call to undefined method Illuminate\Database\Eloquent\Builder::groupLimit() 

### ISSUE THREAD

**Issue by Kwaadpepper** [staudenmeir/eloquent-eager-limit#39]
Using this on laravel 7

      $ranges = Ranges::where('status', 1)->with(['products' => function ($q) {
          $q->limit(1);
      }])->get();  

  BadMethodCallException
  Call to undefined method Illuminate\Database\Eloquent\Builder::groupLimit() 

![image](https://user-images.githubusercontent.com/6019313/112276802-6a7a4580-8c81-11eb-8ee3-65b3640168f2.png)

**Comment by Kwaadpepper** [comment]
Just found the issue https://github.com/staudenmeir/eloquent-eager-limit/issues/1
It solves the problem. It was not obvious on the readme. Thank you.

**Comment by paulocajaiasassolecapedromilto-stack** [comment]
boa tarde.
.
o meu pograma de viegas ang eng esta a vir este erro como faço para resolver
