### ISSUE TITLE
Syntax error or access violation: 1140 Mixing of GROUP columns with no GROUP columns is illegal if there is no GROUP BY clause

### ISSUE THREAD

**Issue by RenoLooijmans** [staudenmeir/eloquent-eager-limit#43]
The following result is reported when the query is executed with strict enabled. If strict is disabled the query works properly. I don't use any group_by clause so I have no idea why this query fails...

SQLSTATE[42000]: Syntax error or access violation: 1140 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause (SQL: select * from (select `orders`.`id`, `orders`.`uuid`, `orders`.`channel_id`, `orders`.`order_nr`, `orders`.`first_name`, `orders`.`last_name`, `orders`.`email`, `orders`.`amount`, `orders`.`payment_costs`, `orders`.`is_demo`, `orders`.`created_at`, `events`.`organisation_id` as `laravel_through_key`, row_number() over (partition by `events`.`organisation_id` order by `created_at` desc) as laravel_row from `orders` inner join `channels` on `channels`.`id` = `orders`.`channel_id` inner join `events` on `events`.`id` = `channels`.`event_id` where `channels`.`deleted_at` is null and `events`.`deleted_at` is null and `events`.`organisation_id` in (2) and `payment_status` = paid and `orders`.`deleted_at` is null) as laravel_table where laravel_row <= 10 order by laravel_row)

**Comment by staudenmeir** [comment]
Are you using MySQL or MariaDB?

**Comment by RenoLooijmans** [comment]
Apologies, I should have stated this in my initial post. I am using MariaDB.

**Comment by staudenmeir** [comment]
Please see the documentation about this issue:
https://github.com/staudenmeir/eloquent-eager-limit#compatibility 

> MariaDB 10.2+: Due to a [bug](https://jira.mariadb.org/browse/MDEV-17785) in MariaDB, the package only works with strict mode disabled.
In your config/database.php file, set 'strict' => false, for the MariaDB connection.

**Comment by RenoLooijmans** [comment]
Ugh.. I should've read the manual properly..

**Comment by staudenmeir** [comment]
The latest MariaDB release fixes this bug and `'strict' => false` is no longer required.
