### ISSUE TITLE
1140 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...)

### ISSUE THREAD

**Issue by msayubi76** [staudenmeir/eloquent-eager-limit#44]
**Product  Model**
`class Product extends Model
{
    use HasFactory;
    use \Staudenmeir\EloquentEagerLimit\HasEagerLimit;
}`

**Category Modal**
`class Category extends Model
{
    use \Staudenmeir\EloquentEagerLimit\HasEagerLimit;

    use HasFactory; 
    public function products()
    {
        return $this->hasMany('App\Models\Product', 'CategoryID', 'CategoryID');
    }
}`

**Actual Query in Controller**
 `return $products = Category::with(['products' => function ($query) {
                $query->offset(5)->limit(10);
            }])->get()`

This error shows up in the Laravel Api
SQLSTATE[42000]: Syntax error or access violation: 1140 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause (SQL: select * from (select *, row_number() over (partition by `products`.`CategoryID`) as laravel_row from `products` where `products`.`CategoryID` in (184, 217, 218, 219, 385, 386, 388, 389, 390, 391, 395, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 424, 425, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 448, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 501, 502, 503, 504, 505, 506, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 521, 522, 523, 524, 525, 526, 527, 528, 530, 531, 533, 534, 535, 536, 537, 538, 540, 541, 542, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 682, 683, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 740, 741, 742, 744, 745, 746, 747, 749, 750, 751, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 777, 780, 781, 782, 783, 788, 789, 791, 793, 794, 795, 796, 797, 798, 799, 801, 802, 803, 804, 809, 810, 811, 812, 813, 815, 816, 817, 819, 820, 821, 822, 824, 825, 826, 828, 829, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1038, 1039, 1040, 1041, 1043, 1044, 1045, 1046, 1047, 1048, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133, 1134, 1137, 1138)) as laravel_table where laravel_row <= 15 and laravel_row > 5 order by laravel_row)

**Comment by staudenmeir** [comment]
Are you using MariaDB?

**Comment by msayubi76** [comment]
I am using phpMyAdmin

**Comment by staudenmeir** [comment]
What database management system are you using? MySQL, MariaDB, PostgreSQL?

**Comment by msayubi76** [comment]
its mySql

**Comment by staudenmeir** [comment]
What's the result of `select version()` in phpMyAdmin?

**Comment by msayubi76** [comment]
version is 10.4.19-MariaDB

**Comment by msayubi76** [comment]
> What database management system are you using? MySQL or MariaDB? What's the result of `select version()` in phpMyAdmin?

I'm sorry it's MariaDB and version is 10.4.19-MariaDB

**Comment by staudenmeir** [comment]
You need to disable strict mode:
https://github.com/staudenmeir/eloquent-eager-limit#compatibility
> MariaDB 10.2+: Due to a bug in MariaDB, the package only works with strict mode disabled.
In your config/database.php file, set 'strict' => false, for the MariaDB connection.

**Comment by staudenmeir** [comment]
What's the result of `select version()` now?

**Comment by msayubi76** [comment]
it's same as above. (10.4.19-MariaDB )

**Comment by staudenmeir** [comment]
That means you are still using MariaDB, not MySQL.

**Comment by msayubi76** [comment]
There is no option for the connection of MariaDB in config/datases.php file. In that file only **sqlite**, **mysql**, **pgsql** and **sqlsrv** connections available. Could you help please help me to find out this issue. 
following is the list of all connections in config/datases.php file just have a look on it. 
`'connections' => [

        'sqlite' => [
            'driver' => 'sqlite',
            'url' => env('DATABASE_URL'),
            'database' => env('DB_DATABASE', database_path('database.sqlite')),
            'prefix' => '',
            'foreign_key_constraints' => env('DB_FOREIGN_KEYS', true),
        ],

        'mysql' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => false,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],

        'pgsql' => [
            'driver' => 'pgsql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'schema' => 'public',
            'sslmode' => 'prefer',
        ],

        'sqlsrv' => [
            'driver' => 'sqlsrv',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '1433'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
        ],

    ],`

**Comment by msayubi76** [comment]
let me know where should I make changes @staudenmeir  .

**Comment by staudenmeir** [comment]
> strict' => false,

That's correct and should work.

Does the query from your first post (`select * from (select *, row_number() ...`) work when run it in phpMyAdmin?

**Comment by msayubi76** [comment]
I run this query in phpMyAdmin and it works.
`SET @row_number = 0; 
SELECT 
    (@row_number:=@row_number + 1) AS num,
    name,
    website
FROM
    users
LIMIT 5;`

**Comment by staudenmeir** [comment]
And the query from your first post?

**Comment by msayubi76** [comment]
I'm using Laravel eloquent to get data. I've already mentioned that query above in question

**Comment by msayubi76** [comment]
@staudenmeir i need your help to resolve this issue

**Comment by msayubi76** [comment]
@staudenmeir , @bonzai , @mvdnbrk , @mpyw  anyone help me ?

**Comment by staudenmeir** [comment]
You need to answer my questions, this is my last attempt:

Does the query from your first post (`select * from (select *, row_number()` ...) work when run it in phpMyAdmin?

**Comment by betterbot-boban** [comment]
> You need to disable strict mode:
> https://github.com/staudenmeir/eloquent-eager-limit#compatibility
> 
> > MariaDB 10.2+: Due to a bug in MariaDB, the package only works with strict mode disabled.
> > In your config/database.php file, set 'strict' => false, for the MariaDB connection.

I had the same issue today on my server and all I did to resolve it was just changing `'strict' => true,`.
My server version: `10.3.31-MariaDB-log-cll-lve`

@staudenmeir thanks for your answer.

**Comment by dev7612** [comment]
> phpMyAdmin

yes it works in phpMyAdmin but didn't work in my Laravel project

**Comment by msayubi76** [comment]
> You need to answer my questions, this is my last attempt:
> 
> Does the query from your first post (`select * from (select *, row_number()` ...) work when run it in phpMyAdmin?

@staudenmeir  yes it works in phpMyAdmin but didn't work in my Laravel project

**Comment by staudenmeir** [comment]
What's the result of `dd(\DB::getConfig('strict'));` in your controller?

**Comment by mansoorkochy** [comment]
Is it a good solution to turn of DBMS strict mode, it got some confusion, isn't compromise DBMS security?

**Comment by staudenmeir** [comment]
It doesn't compromise security, but the workaround also isn't necessary anymore. MariaDB has finally fixed this bug.

**Comment by mansoorkochy** [comment]
I am using MySQL, is there any other solution for this problem?

**Comment by staudenmeir** [comment]
@mansoorkochy Please create a new issue. What version of MySQL are you using? What query are you executing? What's the whole error message?

**Comment by mansoorkochy** [comment]
Okay, I will do

**Comment by dummyuser127** [comment]
> > strict' => false,
> 
> That's correct and should work.
> 
> Does the query from your first post (`select * from (select *, row_number() ...`) work when run it in phpMyAdmin?

It Worked Well..!!!
