### ISSUE TITLE
The trait cannot been seen

### ISSUE THREAD

**Issue by kingdomac** [staudenmeir/eloquent-eager-limit#49]
SQLSTATE[42000]: Syntax error or access violation: 1140 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause

**Comment by staudenmeir** [comment]
What database and version are you using? What query are you running?

**Comment by kingdomac** [comment]
I added a group by for all the columns of the second table result and it works fine.
