### ISSUE TITLE
Duplicate related models aren't filtered with distinct() when combined with eager limit

### ISSUE THREAD

**Issue by nihilsen** [staudenmeir/eloquent-eager-limit#52]
I've added tests in PR #51 that illustrate the issue.

This particularly affects `HasManyDeep` relationships.

In my case, I found we can use `groupBy()` in the following way, to achieve the same effect as `distinct()` for a `BelongsToMany` relationship, but I cannot yet say if it's a general solution.

```PHP
public function cities()
{
    $relation = $this->belongsToMany(City::class, 'user_cities')->limit(2);

    // Filter duplicate results
    return $relation->groupBy(
        $relation->getQualifiedRelatedPivotKeyName(),
        $relation->getQualifiedForeignPivotKeyName()
    );
}
```

**Comment by staudenmeir** [comment]
Thanks for the tests. I don't think I'll be able to support `DISTINCT` here. In general, `DISTINCT` queries are quite the nightmare. `GROUP BY` is the better option and should be able to handle all these cases.

**Comment by nihilsen** [comment]
No worries. When I looked into it, I found that it wasn't as straightforward as I thought. `GROUP BY` works fine for my purposes.

Thanks, and thank you for the many useful Laravel packages!
