### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1140 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...)

### ISSUE THREAD

**Issue by mansoorkochy** [staudenmeir/eloquent-eager-limit#55]
the above error is displayed after installing and using eloquent-eager-limit package trait to both child and parent model, I want to return limited eager loaded relationship on the polymorphic relationship.

MySQL version: 10.4.22-MariaDB
Laravel version: 8.40
error stack trace: [[Link](https://flareapp.io/share/95JqZaB7)](https://flareapp.io/share/95JqZaB7)

my query
`Share::with(['Comment' => function($query){
        $query->take(5);
    }])->where('id',34)->orWhere('id',1)->get();`

Comment model
`public function Commentable()
    {
        return $this->morphTo();
    }`

Post model
`public function Comment()
    {
        return $this->morphMany('App\Models\Comment','commentable','commentable_type','commentable_id')->where('type','comment');
    }`

I hope I have explained better, thanks in advance.

**Comment by staudenmeir** [comment]
The bug has only been fixed in the latest version. In your case, that's `10.4.24`: https://jira.mariadb.org/browse/MDEV-17785

**Comment by mansoorkochy** [comment]
My database version is 20.4.22, shall I update to latest version (20.4.24 or latest) to fix the issue ?

**Comment by staudenmeir** [comment]
Yes.

**Comment by staudenmeir** [comment]
Did the update work?

**Comment by mansoorkochy** [comment]
As of your reply, I have just dockerized my project with the latest MySQL version, and now it works.
thank you
