### ISSUE TITLE
Doesn't work on MariaDB 10.6.4 without disabling strict mode

### ISSUE THREAD

**Issue by KarlisJ** [staudenmeir/eloquent-eager-limit#57]
The readme says

> MySQL 5.5~5.6: Due to a bug in MySQL, the package only works with strict mode disabled.
In your config/database.php file, set 'strict' => false, for the MySQL connection.
MariaDB 10.2+

But I'm getting the same behavior for MariaDB 10.2+ as well. I need to disable the strict mode which is something I'd rather not do. 

Is that incorrectness in readme or problem in my end?

**Comment by staudenmeir** [comment]
This was a bug in MariaDB that has been fixed recently: https://jira.mariadb.org/browse/MDEV-17785
I removed the note from the README after that.
