### ISSUE TITLE
The query still didn't work as expected

### ISSUE THREAD

**Issue by mBabbage** [staudenmeir/eloquent-eager-limit#6]
Hello , I am having a issue with the package , i am using Laravel 5.6.39. 
I have a User and Comment model and trying to limit the number of comments for each user get **only** 10 comments for all the borrowers. Similar to the issue discussed here https://github.com/laravel/framework/issues/18014.

Using your package, I have included the trait in both the User and Comment model but still, it doesn't work as expected. This is how I make the call in my controller:

```php
User::with(['comments' => function($query) {
                $query->latest('id')->limit(3);
            }])->paginate(50)
```

Also, can you extend the limit functionality to work on *paginate()*

**Comment by staudenmeir** [comment]
Please log the executed queries with a tool like https://github.com/barryvdh/laravel-debugbar.

What database and version are you using?

**Comment by mBabbage** [comment]
I checked the queries and it still got 10 comments for all users. I am using mysql 5.7.23

**Comment by staudenmeir** [comment]
Please post the queries.

**Comment by mBabbage** [comment]
select * from `admins` where `id` = 4 limit 1

select count(*) as aggregate from `borrowers` where `borrowers`.`id` LIKE '10234%'

select * from `borrowers` where `borrowers`.`id` LIKE '10234%' limit 50 offset 0

select `id`, `borrower`, `term`, `interest_rate`, `loan_grade`, `amount`, `active`, `date_created`, `funding_time_elapsed` from `loan_requests` where `loan_requests`.`borrower` in (102345, 102346)

select `city_id`, `city_name` from `cities` where `cities`.`city_id` in (0)

select `city_id`, `city_name` from `cities` where `cities`.`city_id` in (0)

select `borrower_id`, `locative`, `cash_inflow`, `cash_outflow` from `borrower_loan_data` where `borrower_loan_data`.`borrower_id` in (102345, 102346)

select `borrower`, `f_name`, `l_name`, `dob`, `phone`, `type` from `bvn_verification_records` where `bvn_verification_records`.`borrower` in (102345, 102346)

select * from `admin_comments` where `entity` = 'BORROWER' and `admin_comments`.`entity_id` in (102345, 102346) order by `id` desc limit 3

select `id`, `username` from `admins` where `admins`.`id` in (4)

select `id`, `owner_id`, `bank_id`, `account_number` from `bank_info` where `card_account` = '1' and `borrower_investor` = '0' and `bank_info`.`owner_id` in (102345, 102346)

select `id`, `bank_name` from `banks` where `banks`.`id` in (2)

**Comment by mBabbage** [comment]
User model
```php
namespace App\Models;

use Illuminate\Support\Facades\DB;
use Reliese\Database\Eloquent\Model as Eloquent;
use \Staudenmeir\EloquentEagerLimit\HasEagerLimit;

class Borrower extends Eloquent
{

    /**
     * Get the comment on this borrower.
     */
    public function comments()
    {
        return $this->hasMany('App\Models\AdminComment', 'entity_id')
            ->where('entity', '=', 'BORROWER');
    }

}

```

Comment model 
```php

namespace App\Models;

use Reliese\Database\Eloquent\Model as Eloquent;
use \Staudenmeir\EloquentEagerLimit\HasEagerLimit;

class AdminComment extends Eloquent
{
	
}

```

**Comment by staudenmeir** [comment]
You are only importing the traits, but not actually using them:

```php
class Borrower extends Eloquent
{
    use \Staudenmeir\EloquentEagerLimit\HasEagerLimit; // or: use HasEagerLimit;
}
```

**Comment by mBabbage** [comment]
Ooohhh... Forgive me for stressing you out. I'm grateful
