### ISSUE TITLE
Trait "Staudenmeir\EloquentEagerLimit\HasEagerLimit" not found

### ISSUE THREAD

**Issue by fingersandmind** [staudenmeir/eloquent-eager-limit#60]

**Comment by staudenmeir** [comment]
What does your class look like?

**Comment by fingersandmind** [comment]
After pushing it to production I got this error 
`PHP Fatal error:  Trait "Staudenmeir\EloquentEagerLimit\HasEagerLimit" not found in /home/runner/work/sample-project/sample-project/app/Models/Product.php on line 27

   Symfony\Component\ErrorHandler\Error\FatalError 


  Trait "Staudenmeir\EloquentEagerLimit\HasEagerLimit" not found
`
It's a Github issue and I can't merge it

**Comment by staudenmeir** [comment]
> After pushing it to production I got this error

Did you install the package on production?
