### ISSUE TITLE
What's the difference between this and Laravel implementation

### ISSUE THREAD

**Issue by exSnake** [staudenmeir/eloquent-eager-limit#61]
I saw that laravel with v8 implemented HasOneOfMany, what's the difference with this package? Should this be added to Readme?

**Comment by staudenmeir** [comment]
`HasOneOfMany` is only an alternative if you want to [retrieve a single record](https://github.com/staudenmeir/eloquent-eager-limit#:~:text=Improve%20the%20performance%20of%20HasOne/HasOneThrough/MorphOne%20relationships%20by%20applying%20limit(1)%3A) (limit = 1), for limits > 1 the package is still necessary.

Do you have a use case in your app?
