### ISSUE TITLE
Using a Lateral join

### ISSUE THREAD

**Issue by bkuhl** [staudenmeir/eloquent-eager-limit#63]
I found this SQL which can help accomplish what this project does with seemingly clean SQL and thought I'd share it in case it's even slightly useful here.

https://twitter.com/tobias_petry/status/1592792857705959424?t=veEpFeWbbbkV_-O1O-gYxw&s=19

Running a fever ATM so I haven't spent time looking at the project source, for all I know this method is already in use. I'm just dropping this link here because I saw some conversation on Twitter the other day about this and wanted to share it but can't find that conversation.

**Comment by staudenmeir** [comment]
Hi @bkuhl,
Thanks for sharing that. I've read about lateral joins but haven't really worked with them.

At the moment, the package supports basically all relevant database engines and so lateral joins would have to offer a significant performance advantage to justify rewriting the package. Of course, that's notoriously hard to measure.

Are you using the package with bigger amounts of data?

> I saw some conversation on Twitter the other day about this and wanted to share it but can't find that conversation

Maybe https://twitter.com/cosmeescobedo/status/1590865088420155392?

**Comment by bkuhl** [comment]
Yep, that was it
