### ISSUE TITLE
The performace is awful

### ISSUE THREAD

**Issue by ISNewton** [staudenmeir/eloquent-eager-limit#65]
I am loading 4 subjects and for every subject I eager laod a post  but the query takes 10 seconds to finish:

Home controller: 
`
static function newst($lang = 1)
    {
        $subs = Subject::with('latestPost')->find([1, 2, 5, 6]);
       ;
        return $all;
    }
`

subject model : 

`
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use \Staudenmeir\EloquentEagerLimit\HasEagerLimit;

class Subject extends Model
{
    protected $table = "subjects";

    use HasEagerLimit;

    public function posts()
    {
        return $this->hasMany(Post::class, 'subject_id');
    }

    public function latestPost()
    {
        return $this->hasOne(Post::class, 'subject_id')->latest('post_date')->limit(1);
    }

    public function slider()
    {
        return $this->hasMany(Post::class, 'subject_id')->latest('post_date')->limit(5);
    }

    public function newst()
    {
        return $this->hasMany(Post::class, 'subject_id');
    }
}

`
post model:

`
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\ImageManager;
use Laravel\Scout\Searchable;
use \Staudenmeir\EloquentEagerLimit\HasEagerLimit;

class Post extends Model
{

    use HasEagerLimit;

   

    protected $table = "posts";
    const UPDATED_AT = 'updated';

    public function subject()
    {
        return $this->belongsTo(Subject::class);
    }
}

`

**Comment by staudenmeir** [comment]
How long does the query take without `->limit(1)`?

How many posts does a subject have on average? Hundreds? Thousands?

What database and version are you using?
