### ISSUE TITLE
Trait method newBaseQueryBuilder has not been applied, because there are collisions with other trait methods

### ISSUE THREAD

**Issue by innoflyweb** [staudenmeir/eloquent-eager-limit#7]
Hey, i'm using this package https://github.com/grimzy/laravel-mysql-spatial along with eloquent-eager-limit and i'm getting this error: 

` Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Trait method newBaseQueryBuilder has not been applied, because there are collisions with other trait methods`

I'm not very good at Traits yet, so i have no idea how to fix this. Can you help?

**Comment by staudenmeir** [comment]
I don't think there's an elegant solution. Try this:

Create a new `Builder` class (e.g. in `app\Builder.php`):

```php
namespace App;

use Grimzy\LaravelMysqlSpatial\Eloquent\SpatialExpression;

class Builder extends \Staudenmeir\EloquentEagerLimit\Builder
{
    protected function cleanBindings(array $bindings)
    {
        $bindings = array_map(function ($binding) {
            return $binding instanceof SpatialExpression ? $binding->getSpatialValue() : $binding;
        }, $bindings);

        return parent::cleanBindings($bindings);
    }
}
```

Then adjust the models that require both traits (there's a `TODO` part at the end):

```php
use Grimzy\LaravelMysqlSpatial\Eloquent\SpatialTrait;
use Illuminate\Database\Connection;
use Illuminate\Database\Eloquent\Model;
use RuntimeException;
use Staudenmeir\EloquentEagerLimit\Grammars\MySqlGrammar;
use Staudenmeir\EloquentEagerLimit\Grammars\PostgresGrammar;
use Staudenmeir\EloquentEagerLimit\Grammars\SQLiteGrammar;
use Staudenmeir\EloquentEagerLimit\Grammars\SqlServerGrammar;

class YourModel extends Model
{
    use SpatialTrait;

    /**
     * Get a new query builder instance for the connection.
     *
     * @return \Illuminate\Database\Query\Builder
     */
    protected function newBaseQueryBuilder()
    {
        $connection = $this->getConnection();

        $grammar = $connection->withTablePrefix($this->getQueryGrammar($connection));

        return new \App\Builder(
            $connection, $grammar, $connection->getPostProcessor()
        );
    }

    /**
     * Get the query grammar.
     *
     * @param  \Illuminate\Database\Connection  $connection
     * @return \Illuminate\Database\Query\Grammars\Grammar
     */
    protected function getQueryGrammar(Connection $connection) {
        $driver = $connection->getDriverName();

        switch ($driver) {
            case 'mysql':
                return new MySqlGrammar;
            case 'pgsql':
                return new PostgresGrammar;
            case 'sqlite':
                return new SQLiteGrammar;
            case 'sqlsrv':
                return new SqlServerGrammar;
        }

        throw new RuntimeException('This database is not supported.'); // @codeCoverageIgnore
    }

    // TODO
    // Add the relationship methods you need from \Staudenmeir\EloquentEagerLimit\HasEagerLimit:
    // newHasMany() etc.
}
```

**Comment by innoflyweb** [comment]
Ok. Thanks, i'll give it a try.

**Comment by innoflyweb** [comment]
Stuck again. I added even added all the methods just in case. Got this error:

```Declaration of App\Stoppage::newHasOne(App\Builder $query, Illuminate\Database\Eloquent\Model $parent, $foreignKey, $localKey) should be compatible with Illuminate\Database\Eloquent\Model::newHasOne(Illuminate\Database\Eloquent\Builder $query, Illuminate\Database\Eloquent\Model $parent, $foreignKey, $localKey)```

**Comment by staudenmeir** [comment]
The relationship methods require a different `Builder` class:

```php
protected function newHasOne(\Illuminate\Database\Eloquent\Builder $query, [...]
```

**Comment by innoflyweb** [comment]
Ok, getting there. Got and sql error now:

```SQLSTATE[42000]: Syntax error or access violation: 1140 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause```

**Comment by staudenmeir** [comment]
What's the whole query?

**Comment by innoflyweb** [comment]
```SQLSTATE[42000]: Syntax error or access violation: 1140 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause (SQL: select * from (select *, row_number() over (partition by `stoppages`.`logger` order by `created_at` desc, `created_at` desc) as laravel_row from `stoppages` where `stoppages`.`logger` in (1, 2, 3, 4, 5, 6, 9, 10, 11, 12, 13, 14, 16, 17, 20, 21, 22, 23, 24, 25, 30, 31, 32, 33, 34, 35, 36, 37, 40, 41, 42, 43, 44, 45, 50, 51, 52, 53, 54, 55, 56, 59, 60, 61, 70, 71, 80, 81, 82, 83, 101, 106, 111, 113, 121, 123, 131, 133, 7001, 7002, 7003, 7004, 7011, 7012, 7013, 7014, 7021, 7022, 7023, 7024, 7031, 7032, 7033, 7034, 7041, 7042, 7043, 7044, 7051, 7052, 7053, 7054, 7061, 7062, 7063, 7064, 7071, 7072, 7073, 7074, 7081, 7082, 7083, 7084, 7091, 7092, 7093, 7094, 7101, 7102, 7103, 7104, 7111, 7112, 7113, 7114, 7121, 7122, 7123, 7124, 7131, 7132, 7133, 7134, 7141, 7142, 7143, 7144, 7151, 7152, 7153, 7154, 7161, 7162, 7163, 7164, 7171, 7172, 7173, 7174, 7181, 7182, 7183, 7184, 7191, 7192, 7193, 7194, 7201, 7202, 7203, 7204)) as laravel_table where laravel_row <= 10 order by laravel_row)```

**Comment by staudenmeir** [comment]
Are you using MariaDB?

**Comment by innoflyweb** [comment]
Jep. Ok is it about the strict key. I set it to false, worked now. Thanks for all the help.

**Comment by mayken** [comment]
I have this bug with HasRecursiveRelationships

**Comment by staudenmeir** [comment]
@mayken Please create a new issue.
