### ISSUE TITLE
Just a question about the generated query

### ISSUE THREAD

**Issue by gabrielpeixoto** [staudenmeir/eloquent-eager-limit#70]
The eager loading feature of Laravel ensures that only a single query is executed instead of N queries. 

Example: 
```php
$books = App\Book::with('authors')->get();
```

For this operation, only two queries will be executed:

```sql
select * from books
 
select * from authors where id in (1, 2, 3, 4, 5, ...)
```
But when I apply a limit to one of the relationships, it restricts the total number of results.

If I use your package and run this code:
```php
$books = App\Book::with(['authors' => function ($query) {
    $query->limit(3);
}])->get();
```

Which queries will be executed?

**Comment by staudenmeir** [comment]
Hi @gabrielpeixoto,
The second looks like this:
https://github.com/staudenmeir/eloquent-eager-limit/blob/master/tests/BuilderTest.php#L17

**Comment by gabrielpeixoto** [comment]
Oh! I will use it, it will be very useful! thanks a lot!
