### ISSUE TITLE
HasEagerLimit trait conflicts with HasJsonRelationships

### ISSUE THREAD

**Issue by EhabAmawi** [staudenmeir/eloquent-eager-limit#71]
```
class Car extends Model
{
    use HasJsonRelationships;
    use HasEagerLimit;
}
```

trying to do this but it gives me the following errors.

```
Trait method 'newHasManyThrough' will not be applied because it collides with 'HasJsonRelationships'
Trait method 'newHasOneThrough' will not be applied because it collides with 'HasJsonRelationships'
Trait method 'newHasMany' will not be applied because it collides with 'HasJsonRelationships'
Trait method 'newHasOne' will not be applied because it collides with 'HasJsonRelationships'
Trait method 'newMorphMany' will not be applied because it collides with 'HasJsonRelationships'
Trait method 'newMorphOne' will not be applied because it collides with 'HasJsonRelationships'
```

**Comment by staudenmeir** [comment]
Hi @EhabAmawi,
Do you want to apply limits to JSON relationships or just use both traits on the same model (but with separate relationships)?

**Comment by EhabAmawi** [comment]
Different relation. In the same relation?

**Comment by staudenmeir** [comment]
Which JSON relationship(s) are you using?

You need to resolve the conflicts by choosing which trait to use for every affected method, e.g.:

```php
class Car extends Model
{
    use HasJsonRelationships, HasEagerLimit {
        HasEagerLimit::newHasMany insteadof HasJsonRelationships;
        HasEagerLimit::newHasOne insteadof HasJsonRelationships;
        HasEagerLimit::newMorphOne insteadof HasJsonRelationships;
        HasEagerLimit::newMorphMany insteadof HasJsonRelationships;
        HasEagerLimit::newHasManyThrough insteadof HasJsonRelationships;
        HasEagerLimit::newHasOneThrough insteadof HasJsonRelationships;
    }
}
```

**Comment by guizoxxv** [comment]
> Which JSON relationship(s) are you using?
> 
> You need to resolve the conflicts by choosing which trait to use for every affected method, e.g.:
> 
> ```
> class Car extends Model
> {
>     use HasJsonRelationships, HasEagerLimit {
>         HasEagerLimit::newHasMany insteadof HasJsonRelationships;
>         HasEagerLimit::newHasOne insteadof HasJsonRelationships;
>         HasEagerLimit::newMorphOne insteadof HasJsonRelationships;
>         HasEagerLimit::newMorphMany insteadof HasJsonRelationships;
>         HasEagerLimit::newHasManyThrough insteadof HasJsonRelationships;
>         HasEagerLimit::newHasOneThrough insteadof HasJsonRelationships;
>     }
> }
> ```

Hello @staudenmeir. This would solve the conflicts, but how can I use both trait methods? For example, this would cause any call to `hasOne` on the `Car` model, to use `HasEagerLimit::newHasOne`. What if I also have relationships that need to use `HasJsonRelationships::newHasOne` in the `Car` model, how can I differentiate? Thank you.

**Comment by staudenmeir** [comment]
@guizoxxv If you want to use both methods, you need to give at least one of them an alias:

```php
class Car extends Model
{
    use HasJsonRelationships, HasEagerLimit {
        HasEagerLimit::newHasOne as newHasOneEagerLimit;
        HasJsonRelationships::newHasOne as newHasOneJson;

        HasEagerLimit::newHasMany insteadof HasJsonRelationships;
        HasEagerLimit::newMorphOne insteadof HasJsonRelationships;
        HasEagerLimit::newMorphMany insteadof HasJsonRelationships;
        HasEagerLimit::newHasManyThrough insteadof HasJsonRelationships;
        HasEagerLimit::newHasOneThrough insteadof HasJsonRelationships;
    }
}
```

**Comment by guizoxxv** [comment]
I tried this approach before, but I found that it might be problematic cause internal methods in one trait that call the conflicted methods would now call the method from the other trait. For example:

```php
Trait A {
    function hello() {
        return 'Hello from A';
    }
}

Trait B {
    function hello() {
        return 'Hello from B';
    }

    function callHello() {
        return $this->hello();
    }
}

class TestClass {
    use A, B {
        A::hello as helloA;
        B::hello as helloB;

        A::hello insteadof B;
    }
}

$testClass = new TestClass();
echo $testClass->callHello(); // Returns 'Hello from A';
```

In your example, internal calls to `newHasOne` inside the `HasJsonRelationships` trait would end up calling `HasEagerLimit::newHasOne`, which can be problematic.

**Comment by staudenmeir** [comment]
Good point. Try this: Copy the whole `hasOne()` method, put it into your model under a different name and replace the `newHasOne()` call in the last line with the correct one.
https://github.com/laravel/framework/blob/b2c197e34aeb7b114b1fdc7fa06debdd9627f446/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php#L101

FYI: Laravel 11 will be released next week and supports eager loading limits natively, i.e. you don't need this package anymore.
