### ISSUE TITLE
Interest in integrating into Laravel 11?

### ISSUE THREAD

**Issue by taylorotwell** [staudenmeir/eloquent-eager-limit#74]
Hey @staudenmeir! Any interest in integrating this into Laravel 11? Seems like it has proven itself as a popular feature now and I'd be up for reviewing a PR to `laravel/framework@master` if you feel up to submitting it?

**Comment by staudenmeir** [comment]
Hi @taylorotwell,
I'll look into it.

**Comment by staudenmeir** [comment]
https://github.com/laravel/framework/pull/49695
