### ISSUE TITLE
Conflict with staudenmeir/eloquent-json-relations

### ISSUE THREAD

**Issue by fagner-acto** [staudenmeir/eloquent-eager-limit#75]
Hey man, it's just a quick question: Have you already heard about the conflict between this package and `staudenmeir/eloquent-json-relations`? We are facing this issue. Do you have any suggestions?

Here is our current stack:
- Laravel: 10
- staudenmeir/eloquent-json-relations: 1.9.1
- staudenmeir/eloquent-eager-limit: 1.8.3

To finish it, thank you for sharing your work, and congratulations on being part of the next Laravel version. You deserved this!

**Comment by staudenmeir** [comment]
Hi @fagner-acto,
Take a look at this issue: #71

**Comment by staudenmeir** [comment]
Hi @fagner-acto,
Do you want to apply limits to JSON relationships or just use both traits on the same model (but with separate relationships)?

**Comment by fagner-acto** [comment]
Hi, thank you for the fast answer. I need to use both traits in the same model (yes, they will be utilized in different relationships).

**Comment by staudenmeir** [comment]
Resolve the conflicts like this: https://github.com/staudenmeir/eloquent-eager-limit/issues/71#issuecomment-1634965460

**Comment by fagner-acto** [comment]
Nice! I appreciate your support.
