### ISSUE TITLE
use HasJsonRelationships and HasEagerLimit

### ISSUE THREAD

**Issue by nAa6666** [staudenmeir/eloquent-eager-limit#79]
Hello, there is a problem, can I somehow solve it?
<img width="1215" alt="Screenshot 2024-12-14 at 16 04 26" src="https://github.com/user-attachments/assets/450bd530-03b0-4280-814b-80fe82c168a4" />

Trait method Staudenmeir\EloquentEagerLimit\HasEagerLimit::newHasOne has not been applied as App\Models\Products\Product::newHasOne, because of collision with Staudenmeir\EloquentJsonRelations\HasJsonRelationships::newHasOne

**Comment by staudenmeir** [comment]
Hi @nAa6666,
Please see https://github.com/staudenmeir/eloquent-eager-limit/issues/71#issuecomment-1634965460.
