### ISSUE TITLE
How to work with Polymorphic Relation?

### ISSUE THREAD

**Issue by Wonkasho** [staudenmeir/eloquent-eager-limit#8]
I opened [this question](https://stackoverflow.com/questions/55051951/laravel-5-6-how-to-fetch-last-x-guest-names-for-room-deal) on stackoverflow and this package seemed to be a solution in all the eager limit loading laravel related issues.

Since the linked question deals with a polymorphic relationship, I was not sure how to set up the relations correctly for this package to do the eager loading limit for the last 3 guests of a room deal, where the stayable_location (room) is polymorphic.

Any idea what the correct setup would be?

**Note**: I mentioned you in the SO question @staudenmeir but wasn't sure if you got notified due to the space in your SO username.

**Comment by staudenmeir** [comment]
I've posted on SO.

SO only allows you to mention users that are already involved in the conversation.
